//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Daedalus.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDaedalusListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class DaedalusBaseListener : IDaedalusListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.daedalusFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDaedalusFile([NotNull] DaedalusParser.DaedalusFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.daedalusFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDaedalusFile([NotNull] DaedalusParser.DaedalusFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDef([NotNull] DaedalusParser.FunctionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDef([NotNull] DaedalusParser.FunctionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.constDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDef([NotNull] DaedalusParser.ConstDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.constDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDef([NotNull] DaedalusParser.ConstDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] DaedalusParser.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] DaedalusParser.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.prototypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrototypeDef([NotNull] DaedalusParser.PrototypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.prototypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrototypeDef([NotNull] DaedalusParser.PrototypeDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.instanceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceDef([NotNull] DaedalusParser.InstanceDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.instanceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceDef([NotNull] DaedalusParser.InstanceDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.instanceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceDecl([NotNull] DaedalusParser.InstanceDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.instanceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceDecl([NotNull] DaedalusParser.InstanceDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] DaedalusParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] DaedalusParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.constArrayDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstArrayDef([NotNull] DaedalusParser.ConstArrayDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.constArrayDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstArrayDef([NotNull] DaedalusParser.ConstArrayDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.constArrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstArrayAssignment([NotNull] DaedalusParser.ConstArrayAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.constArrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstArrayAssignment([NotNull] DaedalusParser.ConstArrayAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.constValueDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstValueDef([NotNull] DaedalusParser.ConstValueDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.constValueDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstValueDef([NotNull] DaedalusParser.ConstValueDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.constValueAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstValueAssignment([NotNull] DaedalusParser.ConstValueAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.constValueAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstValueAssignment([NotNull] DaedalusParser.ConstValueAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.varArrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarArrayDecl([NotNull] DaedalusParser.VarArrayDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.varArrayDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarArrayDecl([NotNull] DaedalusParser.VarArrayDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.varValueDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarValueDecl([NotNull] DaedalusParser.VarValueDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.varValueDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarValueDecl([NotNull] DaedalusParser.VarValueDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] DaedalusParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] DaedalusParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.parameterDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDecl([NotNull] DaedalusParser.ParameterDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.parameterDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDecl([NotNull] DaedalusParser.ParameterDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementBlock([NotNull] DaedalusParser.StatementBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementBlock([NotNull] DaedalusParser.StatementBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] DaedalusParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] DaedalusParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] DaedalusParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] DaedalusParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] DaedalusParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] DaedalusParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.ifCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfCondition([NotNull] DaedalusParser.IfConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.ifCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfCondition([NotNull] DaedalusParser.IfConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseBlock([NotNull] DaedalusParser.ElseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseBlock([NotNull] DaedalusParser.ElseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.elseIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfBlock([NotNull] DaedalusParser.ElseIfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.elseIfBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfBlock([NotNull] DaedalusParser.ElseIfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] DaedalusParser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] DaedalusParser.IfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.ifBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlockStatement([NotNull] DaedalusParser.IfBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.ifBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlockStatement([NotNull] DaedalusParser.IfBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] DaedalusParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] DaedalusParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.funcArgExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArgExpression([NotNull] DaedalusParser.FuncArgExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.funcArgExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArgExpression([NotNull] DaedalusParser.FuncArgExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.expressionBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionBlock([NotNull] DaedalusParser.ExpressionBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.expressionBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionBlock([NotNull] DaedalusParser.ExpressionBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bitMoveExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitMoveExpression([NotNull] DaedalusParser.BitMoveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bitMoveExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitMoveExpression([NotNull] DaedalusParser.BitMoveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>oneArgExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneArgExpression([NotNull] DaedalusParser.OneArgExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>oneArgExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneArgExpression([NotNull] DaedalusParser.OneArgExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqExpression([NotNull] DaedalusParser.EqExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqExpression([NotNull] DaedalusParser.EqExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValExpression([NotNull] DaedalusParser.ValExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValExpression([NotNull] DaedalusParser.ValExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpression([NotNull] DaedalusParser.AddExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpression([NotNull] DaedalusParser.AddExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpression([NotNull] DaedalusParser.CompExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpression([NotNull] DaedalusParser.CompExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>logOrExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogOrExpression([NotNull] DaedalusParser.LogOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>logOrExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogOrExpression([NotNull] DaedalusParser.LogOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>binAndExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinAndExpression([NotNull] DaedalusParser.BinAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>binAndExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinAndExpression([NotNull] DaedalusParser.BinAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>binOrExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinOrExpression([NotNull] DaedalusParser.BinOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>binOrExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinOrExpression([NotNull] DaedalusParser.BinOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultExpression([NotNull] DaedalusParser.MultExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultExpression([NotNull] DaedalusParser.MultExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bracketExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketExpression([NotNull] DaedalusParser.BracketExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bracketExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketExpression([NotNull] DaedalusParser.BracketExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>logAndExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogAndExpression([NotNull] DaedalusParser.LogAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>logAndExpression</c>
	/// labeled alternative in <see cref="DaedalusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogAndExpression([NotNull] DaedalusParser.LogAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.simpleValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleValue([NotNull] DaedalusParser.SimpleValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.simpleValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleValue([NotNull] DaedalusParser.SimpleValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>integerLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteralValue([NotNull] DaedalusParser.IntegerLiteralValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>integerLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteralValue([NotNull] DaedalusParser.IntegerLiteralValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>floatLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteralValue([NotNull] DaedalusParser.FloatLiteralValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>floatLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteralValue([NotNull] DaedalusParser.FloatLiteralValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteralValue([NotNull] DaedalusParser.StringLiteralValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteralValue([NotNull] DaedalusParser.StringLiteralValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nullLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLiteralValue([NotNull] DaedalusParser.NullLiteralValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nullLiteralValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLiteralValue([NotNull] DaedalusParser.NullLiteralValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallValue([NotNull] DaedalusParser.FuncCallValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallValue([NotNull] DaedalusParser.FuncCallValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>complexReferenceValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReferenceValue([NotNull] DaedalusParser.ComplexReferenceValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>complexReferenceValue</c>
	/// labeled alternative in <see cref="DaedalusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReferenceValue([NotNull] DaedalusParser.ComplexReferenceValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.complexReferenceLeftSide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReferenceLeftSide([NotNull] DaedalusParser.ComplexReferenceLeftSideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.complexReferenceLeftSide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReferenceLeftSide([NotNull] DaedalusParser.ComplexReferenceLeftSideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.complexReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReference([NotNull] DaedalusParser.ComplexReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.complexReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReference([NotNull] DaedalusParser.ComplexReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.complexReferenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReferenceNode([NotNull] DaedalusParser.ComplexReferenceNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.complexReferenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReferenceNode([NotNull] DaedalusParser.ComplexReferenceNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReference([NotNull] DaedalusParser.TypeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReference([NotNull] DaedalusParser.TypeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.nameNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameNode([NotNull] DaedalusParser.NameNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.nameNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameNode([NotNull] DaedalusParser.NameNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.referenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceNode([NotNull] DaedalusParser.ReferenceNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.referenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceNode([NotNull] DaedalusParser.ReferenceNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.assigmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssigmentOperator([NotNull] DaedalusParser.AssigmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.assigmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssigmentOperator([NotNull] DaedalusParser.AssigmentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.addOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddOperator([NotNull] DaedalusParser.AddOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.addOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddOperator([NotNull] DaedalusParser.AddOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.bitMoveOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitMoveOperator([NotNull] DaedalusParser.BitMoveOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.bitMoveOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitMoveOperator([NotNull] DaedalusParser.BitMoveOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.compOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOperator([NotNull] DaedalusParser.CompOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.compOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOperator([NotNull] DaedalusParser.CompOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.eqOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqOperator([NotNull] DaedalusParser.EqOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.eqOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqOperator([NotNull] DaedalusParser.EqOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.oneArgOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneArgOperator([NotNull] DaedalusParser.OneArgOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.oneArgOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneArgOperator([NotNull] DaedalusParser.OneArgOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.multOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultOperator([NotNull] DaedalusParser.MultOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.multOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultOperator([NotNull] DaedalusParser.MultOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.binAndOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinAndOperator([NotNull] DaedalusParser.BinAndOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.binAndOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinAndOperator([NotNull] DaedalusParser.BinAndOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.binOrOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinOrOperator([NotNull] DaedalusParser.BinOrOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.binOrOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinOrOperator([NotNull] DaedalusParser.BinOrOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.logAndOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogAndOperator([NotNull] DaedalusParser.LogAndOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.logAndOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogAndOperator([NotNull] DaedalusParser.LogAndOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParser.logOrOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogOrOperator([NotNull] DaedalusParser.LogOrOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParser.logOrOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogOrOperator([NotNull] DaedalusParser.LogOrOperatorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
