//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/grzeg/Source/Repos/DaedalusCompiler/src/Parser\Daedalus.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class DaedalusParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, Const=34, Var=35, If=36, Int=37, Else=38, Func=39, 
		String=40, Class=41, Void=42, Return=43, Float=44, Prototype=45, Instance=46, 
		Null=47, Identifier=48, IntegerLiteral=49, FloatLiteral=50, StringLiteral=51, 
		Whitespace=52, Newline=53, BlockComment=54, LineComment=55;
	public const int
		RULE_daedalusFile = 0, RULE_functionDef = 1, RULE_constDef = 2, RULE_classDef = 3, 
		RULE_prototypeDef = 4, RULE_instanceDef = 5, RULE_instanceDecl = 6, RULE_varDecl = 7, 
		RULE_parameterList = 8, RULE_parameterDecl = 9, RULE_statementBlock = 10, 
		RULE_statement = 11, RULE_funcCall = 12, RULE_assignment = 13, RULE_ifBlock = 14, 
		RULE_returnStatement = 15, RULE_constAssignment = 16, RULE_arrayLiteral = 17, 
		RULE_expression = 18, RULE_simpleValue = 19, RULE_value = 20, RULE_complexReference = 21, 
		RULE_complexReferenceNode = 22, RULE_typeReference = 23, RULE_nameNode = 24, 
		RULE_referenceNode = 25;
	public static readonly string[] ruleNames = {
		"daedalusFile", "functionDef", "constDef", "classDef", "prototypeDef", 
		"instanceDef", "instanceDecl", "varDecl", "parameterList", "parameterDecl", 
		"statementBlock", "statement", "funcCall", "assignment", "ifBlock", "returnStatement", 
		"constAssignment", "arrayLiteral", "expression", "simpleValue", "value", 
		"complexReference", "complexReferenceNode", "typeReference", "nameNode", 
		"referenceNode"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'['", "']'", "'{'", "'}'", "'('", "')'", "','", "'='", "'+='", 
		"'-='", "'*='", "'/='", "'-'", "'!'", "'~'", "'+'", "'*'", "'/'", "'%'", 
		"'<<'", "'>>'", "'<'", "'>'", "'<='", "'>='", "'=='", "'!='", "'&'", "'|'", 
		"'&&'", "'||'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "Const", "Var", 
		"If", "Int", "Else", "Func", "String", "Class", "Void", "Return", "Float", 
		"Prototype", "Instance", "Null", "Identifier", "IntegerLiteral", "FloatLiteral", 
		"StringLiteral", "Whitespace", "Newline", "BlockComment", "LineComment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Daedalus.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DaedalusParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DaedalusParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DaedalusParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class DaedalusFileContext : ParserRuleContext {
		public FunctionDefContext[] functionDef() {
			return GetRuleContexts<FunctionDefContext>();
		}
		public FunctionDefContext functionDef(int i) {
			return GetRuleContext<FunctionDefContext>(i);
		}
		public ConstDefContext[] constDef() {
			return GetRuleContexts<ConstDefContext>();
		}
		public ConstDefContext constDef(int i) {
			return GetRuleContext<ConstDefContext>(i);
		}
		public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public ClassDefContext[] classDef() {
			return GetRuleContexts<ClassDefContext>();
		}
		public ClassDefContext classDef(int i) {
			return GetRuleContext<ClassDefContext>(i);
		}
		public PrototypeDefContext[] prototypeDef() {
			return GetRuleContexts<PrototypeDefContext>();
		}
		public PrototypeDefContext prototypeDef(int i) {
			return GetRuleContext<PrototypeDefContext>(i);
		}
		public InstanceDefContext[] instanceDef() {
			return GetRuleContexts<InstanceDefContext>();
		}
		public InstanceDefContext instanceDef(int i) {
			return GetRuleContext<InstanceDefContext>(i);
		}
		public InstanceDeclContext[] instanceDecl() {
			return GetRuleContexts<InstanceDeclContext>();
		}
		public InstanceDeclContext instanceDecl(int i) {
			return GetRuleContext<InstanceDeclContext>(i);
		}
		public DaedalusFileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_daedalusFile; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterDaedalusFile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitDaedalusFile(this);
		}
	}

	[RuleVersion(0)]
	public DaedalusFileContext daedalusFile() {
		DaedalusFileContext _localctx = new DaedalusFileContext(Context, State);
		EnterRule(_localctx, 0, RULE_daedalusFile);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 59;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
					case 1:
						{
						State = 52; functionDef();
						}
						break;
					case 2:
						{
						State = 53; constDef();
						}
						break;
					case 3:
						{
						State = 54; varDecl();
						}
						break;
					case 4:
						{
						State = 55; classDef();
						}
						break;
					case 5:
						{
						State = 56; prototypeDef();
						}
						break;
					case 6:
						{
						State = 57; instanceDef();
						}
						break;
					case 7:
						{
						State = 58; instanceDecl();
						}
						break;
					}
					State = 61; Match(T__0);
					}
					} 
				}
				State = 67;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefContext : ParserRuleContext {
		public ITerminalNode Func() { return GetToken(DaedalusParser.Func, 0); }
		public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ParameterListContext parameterList() {
			return GetRuleContext<ParameterListContext>(0);
		}
		public StatementBlockContext statementBlock() {
			return GetRuleContext<StatementBlockContext>(0);
		}
		public FunctionDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterFunctionDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitFunctionDef(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDefContext functionDef() {
		FunctionDefContext _localctx = new FunctionDefContext(Context, State);
		EnterRule(_localctx, 2, RULE_functionDef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68; Match(Func);
			State = 69; typeReference();
			State = 70; nameNode();
			State = 71; parameterList();
			State = 72; statementBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstDefContext : ParserRuleContext {
		public ITerminalNode Const() { return GetToken(DaedalusParser.Const, 0); }
		public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ConstAssignmentContext constAssignment() {
			return GetRuleContext<ConstAssignmentContext>(0);
		}
		public SimpleValueContext simpleValue() {
			return GetRuleContext<SimpleValueContext>(0);
		}
		public ConstDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterConstDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitConstDef(this);
		}
	}

	[RuleVersion(0)]
	public ConstDefContext constDef() {
		ConstDefContext _localctx = new ConstDefContext(Context, State);
		EnterRule(_localctx, 4, RULE_constDef);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74; Match(Const);
			State = 75; typeReference();
			State = 76; nameNode();
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 77; Match(T__1);
				State = 78; simpleValue();
				State = 79; Match(T__2);
				}
			}

			State = 83; constAssignment();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDefContext : ParserRuleContext {
		public ITerminalNode Class() { return GetToken(DaedalusParser.Class, 0); }
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public ClassDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterClassDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitClassDef(this);
		}
	}

	[RuleVersion(0)]
	public ClassDefContext classDef() {
		ClassDefContext _localctx = new ClassDefContext(Context, State);
		EnterRule(_localctx, 6, RULE_classDef);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; Match(Class);
			State = 86; nameNode();
			State = 87; Match(T__3);
			State = 93;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 88; varDecl();
					State = 89; Match(T__0);
					}
					} 
				}
				State = 95;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			State = 96; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrototypeDefContext : ParserRuleContext {
		public ITerminalNode Prototype() { return GetToken(DaedalusParser.Prototype, 0); }
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ReferenceNodeContext referenceNode() {
			return GetRuleContext<ReferenceNodeContext>(0);
		}
		public AssignmentContext[] assignment() {
			return GetRuleContexts<AssignmentContext>();
		}
		public AssignmentContext assignment(int i) {
			return GetRuleContext<AssignmentContext>(i);
		}
		public FuncCallContext[] funcCall() {
			return GetRuleContexts<FuncCallContext>();
		}
		public FuncCallContext funcCall(int i) {
			return GetRuleContext<FuncCallContext>(i);
		}
		public PrototypeDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prototypeDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterPrototypeDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitPrototypeDef(this);
		}
	}

	[RuleVersion(0)]
	public PrototypeDefContext prototypeDef() {
		PrototypeDefContext _localctx = new PrototypeDefContext(Context, State);
		EnterRule(_localctx, 8, RULE_prototypeDef);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 98; Match(Prototype);
			State = 99; nameNode();
			State = 100; Match(T__5);
			State = 101; referenceNode();
			State = 102; Match(T__6);
			State = 103; Match(T__3);
			State = 112;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 106;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
					case 1:
						{
						State = 104; assignment();
						}
						break;
					case 2:
						{
						State = 105; funcCall();
						}
						break;
					}
					State = 108; Match(T__0);
					}
					} 
				}
				State = 114;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			State = 115; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstanceDefContext : ParserRuleContext {
		public ITerminalNode Instance() { return GetToken(DaedalusParser.Instance, 0); }
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ReferenceNodeContext referenceNode() {
			return GetRuleContext<ReferenceNodeContext>(0);
		}
		public AssignmentContext[] assignment() {
			return GetRuleContexts<AssignmentContext>();
		}
		public AssignmentContext assignment(int i) {
			return GetRuleContext<AssignmentContext>(i);
		}
		public FuncCallContext[] funcCall() {
			return GetRuleContexts<FuncCallContext>();
		}
		public FuncCallContext funcCall(int i) {
			return GetRuleContext<FuncCallContext>(i);
		}
		public InstanceDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instanceDef; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterInstanceDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitInstanceDef(this);
		}
	}

	[RuleVersion(0)]
	public InstanceDefContext instanceDef() {
		InstanceDefContext _localctx = new InstanceDefContext(Context, State);
		EnterRule(_localctx, 10, RULE_instanceDef);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 117; Match(Instance);
			State = 118; nameNode();
			State = 119; Match(T__5);
			State = 120; referenceNode();
			State = 121; Match(T__6);
			State = 122; Match(T__3);
			State = 131;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 125;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
					case 1:
						{
						State = 123; assignment();
						}
						break;
					case 2:
						{
						State = 124; funcCall();
						}
						break;
					}
					State = 127; Match(T__0);
					}
					} 
				}
				State = 133;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			State = 134; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstanceDeclContext : ParserRuleContext {
		public ITerminalNode Instance() { return GetToken(DaedalusParser.Instance, 0); }
		public NameNodeContext[] nameNode() {
			return GetRuleContexts<NameNodeContext>();
		}
		public NameNodeContext nameNode(int i) {
			return GetRuleContext<NameNodeContext>(i);
		}
		public ReferenceNodeContext[] referenceNode() {
			return GetRuleContexts<ReferenceNodeContext>();
		}
		public ReferenceNodeContext referenceNode(int i) {
			return GetRuleContext<ReferenceNodeContext>(i);
		}
		public InstanceDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instanceDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterInstanceDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitInstanceDecl(this);
		}
	}

	[RuleVersion(0)]
	public InstanceDeclContext instanceDecl() {
		InstanceDeclContext _localctx = new InstanceDeclContext(Context, State);
		EnterRule(_localctx, 12, RULE_instanceDecl);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 136; Match(Instance);
			State = 137; nameNode();
			State = 142;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 138; Match(T__7);
					State = 139; referenceNode();
					}
					} 
				}
				State = 144;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			State = 145; Match(T__5);
			State = 146; nameNode();
			State = 147; Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclContext : ParserRuleContext {
		public ITerminalNode Var() { return GetToken(DaedalusParser.Var, 0); }
		public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		public NameNodeContext[] nameNode() {
			return GetRuleContexts<NameNodeContext>();
		}
		public NameNodeContext nameNode(int i) {
			return GetRuleContext<NameNodeContext>(i);
		}
		public SimpleValueContext simpleValue() {
			return GetRuleContext<SimpleValueContext>(0);
		}
		public VarDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterVarDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitVarDecl(this);
		}
	}

	[RuleVersion(0)]
	public VarDeclContext varDecl() {
		VarDeclContext _localctx = new VarDeclContext(Context, State);
		EnterRule(_localctx, 14, RULE_varDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149; Match(Var);
			State = 150; typeReference();
			State = 151; nameNode();
			State = 163;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				{
				State = 152; Match(T__1);
				State = 153; simpleValue();
				State = 154; Match(T__2);
				}
				}
				break;
			case 2:
				{
				State = 160;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__7) {
					{
					{
					State = 156; Match(T__7);
					State = 157; nameNode();
					}
					}
					State = 162;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterListContext : ParserRuleContext {
		public ParameterDeclContext[] parameterDecl() {
			return GetRuleContexts<ParameterDeclContext>();
		}
		public ParameterDeclContext parameterDecl(int i) {
			return GetRuleContext<ParameterDeclContext>(i);
		}
		public ParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterParameterList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitParameterList(this);
		}
	}

	[RuleVersion(0)]
	public ParameterListContext parameterList() {
		ParameterListContext _localctx = new ParameterListContext(Context, State);
		EnterRule(_localctx, 16, RULE_parameterList);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 165; Match(T__5);
			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Var) {
				{
				State = 166; parameterDecl();
				State = 171;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1+1 ) {
						{
						{
						State = 167; Match(T__7);
						State = 168; parameterDecl();
						}
						} 
					}
					State = 173;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				}
				}
			}

			State = 176; Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterDeclContext : ParserRuleContext {
		public ITerminalNode Var() { return GetToken(DaedalusParser.Var, 0); }
		public TypeReferenceContext typeReference() {
			return GetRuleContext<TypeReferenceContext>(0);
		}
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public SimpleValueContext simpleValue() {
			return GetRuleContext<SimpleValueContext>(0);
		}
		public ParameterDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterParameterDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitParameterDecl(this);
		}
	}

	[RuleVersion(0)]
	public ParameterDeclContext parameterDecl() {
		ParameterDeclContext _localctx = new ParameterDeclContext(Context, State);
		EnterRule(_localctx, 18, RULE_parameterDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178; Match(Var);
			State = 179; typeReference();
			State = 180; nameNode();
			State = 185;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 181; Match(T__1);
				State = 182; simpleValue();
				State = 183; Match(T__2);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementBlockContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public IfBlockContext[] ifBlock() {
			return GetRuleContexts<IfBlockContext>();
		}
		public IfBlockContext ifBlock(int i) {
			return GetRuleContext<IfBlockContext>(i);
		}
		public StatementBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statementBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterStatementBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitStatementBlock(this);
		}
	}

	[RuleVersion(0)]
	public StatementBlockContext statementBlock() {
		StatementBlockContext _localctx = new StatementBlockContext(Context, State);
		EnterRule(_localctx, 20, RULE_statementBlock);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 187; Match(T__3);
			State = 199;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 195;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case T__5:
					case T__13:
					case T__14:
					case T__15:
					case T__16:
					case Const:
					case Var:
					case Return:
					case Null:
					case Identifier:
					case IntegerLiteral:
					case FloatLiteral:
					case StringLiteral:
						{
						{
						State = 188; statement();
						State = 189; Match(T__0);
						}
						}
						break;
					case If:
						{
						{
						State = 191; ifBlock();
						State = 193;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==T__0) {
							{
							State = 192; Match(T__0);
							}
						}

						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					} 
				}
				State = 201;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
			}
			State = 202; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public FuncCallContext funcCall() {
			return GetRuleContext<FuncCallContext>(0);
		}
		public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public ReturnStatementContext returnStatement() {
			return GetRuleContext<ReturnStatementContext>(0);
		}
		public ConstDefContext constDef() {
			return GetRuleContext<ConstDefContext>(0);
		}
		public VarDeclContext varDecl() {
			return GetRuleContext<VarDeclContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_statement);
		try {
			State = 210;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 204; funcCall();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 205; assignment();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 206; returnStatement();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 207; constDef();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 208; varDecl();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 209; expression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FuncCallContext : ParserRuleContext {
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public FuncCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funcCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterFuncCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitFuncCall(this);
		}
	}

	[RuleVersion(0)]
	public FuncCallContext funcCall() {
		FuncCallContext _localctx = new FuncCallContext(Context, State);
		EnterRule(_localctx, 24, RULE_funcCall);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 212; nameNode();
			State = 213; Match(T__5);
			State = 222;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16) | (1L << Null) | (1L << Identifier) | (1L << IntegerLiteral) | (1L << FloatLiteral) | (1L << StringLiteral))) != 0)) {
				{
				State = 214; expression(0);
				State = 219;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
				while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1+1 ) {
						{
						{
						State = 215; Match(T__7);
						State = 216; expression(0);
						}
						} 
					}
					State = 221;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
				}
				}
			}

			State = 224; Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		public ComplexReferenceContext complexReference() {
			return GetRuleContext<ComplexReferenceContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 26, RULE_assignment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 226; complexReference();
			State = 227;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 228; expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfBlockContext : ParserRuleContext {
		public ITerminalNode[] If() { return GetTokens(DaedalusParser.If); }
		public ITerminalNode If(int i) {
			return GetToken(DaedalusParser.If, i);
		}
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public StatementBlockContext[] statementBlock() {
			return GetRuleContexts<StatementBlockContext>();
		}
		public StatementBlockContext statementBlock(int i) {
			return GetRuleContext<StatementBlockContext>(i);
		}
		public ITerminalNode[] Else() { return GetTokens(DaedalusParser.Else); }
		public ITerminalNode Else(int i) {
			return GetToken(DaedalusParser.Else, i);
		}
		public IfBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterIfBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitIfBlock(this);
		}
	}

	[RuleVersion(0)]
	public IfBlockContext ifBlock() {
		IfBlockContext _localctx = new IfBlockContext(Context, State);
		EnterRule(_localctx, 28, RULE_ifBlock);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 230; Match(If);
			State = 231; expression(0);
			State = 232; statementBlock();
			State = 240;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 233; Match(Else);
					State = 234; Match(If);
					State = 235; expression(0);
					State = 236; statementBlock();
					}
					} 
				}
				State = 242;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			State = 245;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Else) {
				{
				State = 243; Match(Else);
				State = 244; statementBlock();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnStatementContext : ParserRuleContext {
		public ITerminalNode Return() { return GetToken(DaedalusParser.Return, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterReturnStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitReturnStatement(this);
		}
	}

	[RuleVersion(0)]
	public ReturnStatementContext returnStatement() {
		ReturnStatementContext _localctx = new ReturnStatementContext(Context, State);
		EnterRule(_localctx, 30, RULE_returnStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 247; Match(Return);
			State = 249;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16) | (1L << Null) | (1L << Identifier) | (1L << IntegerLiteral) | (1L << FloatLiteral) | (1L << StringLiteral))) != 0)) {
				{
				State = 248; expression(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstAssignmentContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArrayLiteralContext arrayLiteral() {
			return GetRuleContext<ArrayLiteralContext>(0);
		}
		public ConstAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constAssignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterConstAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitConstAssignment(this);
		}
	}

	[RuleVersion(0)]
	public ConstAssignmentContext constAssignment() {
		ConstAssignmentContext _localctx = new ConstAssignmentContext(Context, State);
		EnterRule(_localctx, 32, RULE_constAssignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251; Match(T__8);
			State = 254;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
			case T__13:
			case T__14:
			case T__15:
			case T__16:
			case Null:
			case Identifier:
			case IntegerLiteral:
			case FloatLiteral:
			case StringLiteral:
				{
				State = 252; expression(0);
				}
				break;
			case T__3:
				{
				State = 253; arrayLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayLiteralContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArrayLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayLiteral; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterArrayLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitArrayLiteral(this);
		}
	}

	[RuleVersion(0)]
	public ArrayLiteralContext arrayLiteral() {
		ArrayLiteralContext _localctx = new ArrayLiteralContext(Context, State);
		EnterRule(_localctx, 34, RULE_arrayLiteral);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 256; Match(T__3);
			{
			State = 257; expression(0);
			State = 262;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 258; Match(T__7);
					State = 259; expression(0);
					}
					} 
				}
				State = 264;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			}
			}
			State = 265; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public NameNodeContext nameNode() {
			return GetRuleContext<NameNodeContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 36;
		EnterRecursionRule(_localctx, 36, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 276;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				{
				State = 268; Match(T__5);
				State = 269; expression(0);
				State = 270; Match(T__6);
				}
				break;
			case 2:
				{
				State = 272;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 273; expression(9);
				}
				break;
			case 3:
				{
				State = 274; value();
				}
				break;
			case 4:
				{
				State = 275; nameNode();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 298;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 296;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
					case 1:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 278;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 279;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__17) | (1L << T__18) | (1L << T__19))) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 280; expression(9);
						}
						break;
					case 2:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 281;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 282;
						_la = TokenStream.LA(1);
						if ( !(_la==T__13 || _la==T__16) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 283; expression(8);
						}
						break;
					case 3:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 284;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 285;
						_la = TokenStream.LA(1);
						if ( !(_la==T__20 || _la==T__21) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 286; expression(7);
						}
						break;
					case 4:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 287;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 288;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__22) | (1L << T__23) | (1L << T__24) | (1L << T__25))) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 289; expression(6);
						}
						break;
					case 5:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 290;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 291;
						_la = TokenStream.LA(1);
						if ( !(_la==T__26 || _la==T__27) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 292; expression(5);
						}
						break;
					case 6:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 293;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 294;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << T__31))) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 295; expression(4);
						}
						break;
					}
					} 
				}
				State = 300;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class SimpleValueContext : ParserRuleContext {
		public ITerminalNode IntegerLiteral() { return GetToken(DaedalusParser.IntegerLiteral, 0); }
		public ReferenceNodeContext referenceNode() {
			return GetRuleContext<ReferenceNodeContext>(0);
		}
		public SimpleValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterSimpleValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitSimpleValue(this);
		}
	}

	[RuleVersion(0)]
	public SimpleValueContext simpleValue() {
		SimpleValueContext _localctx = new SimpleValueContext(Context, State);
		EnterRule(_localctx, 38, RULE_simpleValue);
		try {
			State = 303;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IntegerLiteral:
				EnterOuterAlt(_localctx, 1);
				{
				State = 301; Match(IntegerLiteral);
				}
				break;
			case Identifier:
				EnterOuterAlt(_localctx, 2);
				{
				State = 302; referenceNode();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ITerminalNode IntegerLiteral() { return GetToken(DaedalusParser.IntegerLiteral, 0); }
		public ITerminalNode FloatLiteral() { return GetToken(DaedalusParser.FloatLiteral, 0); }
		public ITerminalNode StringLiteral() { return GetToken(DaedalusParser.StringLiteral, 0); }
		public ITerminalNode Null() { return GetToken(DaedalusParser.Null, 0); }
		public FuncCallContext funcCall() {
			return GetRuleContext<FuncCallContext>(0);
		}
		public ComplexReferenceContext complexReference() {
			return GetRuleContext<ComplexReferenceContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 40, RULE_value);
		try {
			State = 311;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 305; Match(IntegerLiteral);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 306; Match(FloatLiteral);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 307; Match(StringLiteral);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 308; Match(Null);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 309; funcCall();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 310; complexReference();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexReferenceContext : ParserRuleContext {
		public ComplexReferenceNodeContext[] complexReferenceNode() {
			return GetRuleContexts<ComplexReferenceNodeContext>();
		}
		public ComplexReferenceNodeContext complexReferenceNode(int i) {
			return GetRuleContext<ComplexReferenceNodeContext>(i);
		}
		public ComplexReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexReference; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterComplexReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitComplexReference(this);
		}
	}

	[RuleVersion(0)]
	public ComplexReferenceContext complexReference() {
		ComplexReferenceContext _localctx = new ComplexReferenceContext(Context, State);
		EnterRule(_localctx, 42, RULE_complexReference);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 313; complexReferenceNode();
			State = 316;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
			case 1:
				{
				State = 314; Match(T__32);
				State = 315; complexReferenceNode();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComplexReferenceNodeContext : ParserRuleContext {
		public ReferenceNodeContext referenceNode() {
			return GetRuleContext<ReferenceNodeContext>(0);
		}
		public SimpleValueContext simpleValue() {
			return GetRuleContext<SimpleValueContext>(0);
		}
		public ComplexReferenceNodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_complexReferenceNode; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterComplexReferenceNode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitComplexReferenceNode(this);
		}
	}

	[RuleVersion(0)]
	public ComplexReferenceNodeContext complexReferenceNode() {
		ComplexReferenceNodeContext _localctx = new ComplexReferenceNodeContext(Context, State);
		EnterRule(_localctx, 44, RULE_complexReferenceNode);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 318; referenceNode();
			State = 323;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				{
				State = 319; Match(T__1);
				State = 320; simpleValue();
				State = 321; Match(T__2);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeReferenceContext : ParserRuleContext {
		public ReferenceNodeContext referenceNode() {
			return GetRuleContext<ReferenceNodeContext>(0);
		}
		public ITerminalNode Void() { return GetToken(DaedalusParser.Void, 0); }
		public ITerminalNode Int() { return GetToken(DaedalusParser.Int, 0); }
		public ITerminalNode Float() { return GetToken(DaedalusParser.Float, 0); }
		public ITerminalNode String() { return GetToken(DaedalusParser.String, 0); }
		public ITerminalNode Func() { return GetToken(DaedalusParser.Func, 0); }
		public ITerminalNode Instance() { return GetToken(DaedalusParser.Instance, 0); }
		public TypeReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeReference; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterTypeReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitTypeReference(this);
		}
	}

	[RuleVersion(0)]
	public TypeReferenceContext typeReference() {
		TypeReferenceContext _localctx = new TypeReferenceContext(Context, State);
		EnterRule(_localctx, 46, RULE_typeReference);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 332;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Identifier:
				{
				State = 325; referenceNode();
				}
				break;
			case Void:
				{
				State = 326; Match(Void);
				}
				break;
			case Int:
				{
				State = 327; Match(Int);
				}
				break;
			case Float:
				{
				State = 328; Match(Float);
				}
				break;
			case String:
				{
				State = 329; Match(String);
				}
				break;
			case Func:
				{
				State = 330; Match(Func);
				}
				break;
			case Instance:
				{
				State = 331; Match(Instance);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameNodeContext : ParserRuleContext {
		public ITerminalNode Identifier() { return GetToken(DaedalusParser.Identifier, 0); }
		public NameNodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nameNode; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterNameNode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitNameNode(this);
		}
	}

	[RuleVersion(0)]
	public NameNodeContext nameNode() {
		NameNodeContext _localctx = new NameNodeContext(Context, State);
		EnterRule(_localctx, 48, RULE_nameNode);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 334; Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReferenceNodeContext : ParserRuleContext {
		public ITerminalNode Identifier() { return GetToken(DaedalusParser.Identifier, 0); }
		public ReferenceNodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_referenceNode; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.EnterReferenceNode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDaedalusListener typedListener = listener as IDaedalusListener;
			if (typedListener != null) typedListener.ExitReferenceNode(this);
		}
	}

	[RuleVersion(0)]
	public ReferenceNodeContext referenceNode() {
		ReferenceNodeContext _localctx = new ReferenceNodeContext(Context, State);
		EnterRule(_localctx, 50, RULE_referenceNode);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 336; Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 18: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 8);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		case 5: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x39', '\x155', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '>', '\n', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x42', '\n', '\x2', '\f', 
		'\x2', '\xE', '\x2', '\x45', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x5', '\x4', 'T', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\a', '\x5', '^', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 
		'\x61', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x5', '\x6', 'm', '\n', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\a', '\x6', 'q', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 't', 
		'\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x5', '\a', '\x80', '\n', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 
		'\x84', '\n', '\a', '\f', '\a', '\xE', '\a', '\x87', '\v', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\a', '\b', '\x8F', '\n', '\b', '\f', '\b', '\xE', '\b', '\x92', '\v', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\xA1', '\n', '\t', '\f', 
		'\t', '\xE', '\t', '\xA4', '\v', '\t', '\x5', '\t', '\xA6', '\n', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\a', '\n', '\xAC', 
		'\n', '\n', '\f', '\n', '\xE', '\n', '\xAF', '\v', '\n', '\x5', '\n', 
		'\xB1', '\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', 
		'\v', '\xBC', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', '\xC4', '\n', '\f', '\x5', 
		'\f', '\xC6', '\n', '\f', '\a', '\f', '\xC8', '\n', '\f', '\f', '\f', 
		'\xE', '\f', '\xCB', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', 
		'\r', '\xD5', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\a', '\xE', '\xDC', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\xDF', '\v', '\xE', '\x5', '\xE', '\xE1', '\n', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\xF1', 
		'\n', '\x10', '\f', '\x10', '\xE', '\x10', '\xF4', '\v', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x5', '\x10', '\xF8', '\n', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\xFC', '\n', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x5', '\x12', '\x101', '\n', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\x107', '\n', 
		'\x13', '\f', '\x13', '\xE', '\x13', '\x10A', '\v', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x5', '\x14', '\x117', '\n', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\a', '\x14', '\x12B', '\n', '\x14', '\f', '\x14', '\xE', '\x14', 
		'\x12E', '\v', '\x14', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\x132', 
		'\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\x13A', '\n', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x13F', '\n', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x5', '\x18', '\x146', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x5', 
		'\x19', '\x14F', '\n', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\f', '\x43', '_', 'r', '\x85', '\x90', 
		'\xAD', '\xC9', '\xDD', '\xF2', '\x108', '\x3', '&', '\x1C', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', 
		'\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', 
		'\x32', '\x34', '\x2', '\n', '\x3', '\x2', '\v', '\xF', '\x3', '\x2', 
		'\x10', '\x13', '\x3', '\x2', '\x14', '\x16', '\x4', '\x2', '\x10', '\x10', 
		'\x13', '\x13', '\x3', '\x2', '\x17', '\x18', '\x3', '\x2', '\x19', '\x1C', 
		'\x3', '\x2', '\x1D', '\x1E', '\x3', '\x2', '\x1F', '\"', '\x2', '\x174', 
		'\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x4', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\x6', 'L', '\x3', '\x2', '\x2', '\x2', '\b', 'W', '\x3', 
		'\x2', '\x2', '\x2', '\n', '\x64', '\x3', '\x2', '\x2', '\x2', '\f', 'w', 
		'\x3', '\x2', '\x2', '\x2', '\xE', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x10', '\x97', '\x3', '\x2', '\x2', '\x2', '\x12', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\xB4', '\x3', '\x2', '\x2', '\x2', '\x16', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\xD4', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\xD6', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xE4', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\xE8', '\x3', '\x2', '\x2', '\x2', ' ', '\xF9', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\xFD', '\x3', '\x2', '\x2', '\x2', 
		'$', '\x102', '\x3', '\x2', '\x2', '\x2', '&', '\x116', '\x3', '\x2', 
		'\x2', '\x2', '(', '\x131', '\x3', '\x2', '\x2', '\x2', '*', '\x139', 
		'\x3', '\x2', '\x2', '\x2', ',', '\x13B', '\x3', '\x2', '\x2', '\x2', 
		'.', '\x140', '\x3', '\x2', '\x2', '\x2', '\x30', '\x14E', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x150', '\x3', '\x2', '\x2', '\x2', '\x34', '\x152', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '>', '\x5', '\x4', '\x3', '\x2', '\x37', 
		'>', '\x5', '\x6', '\x4', '\x2', '\x38', '>', '\x5', '\x10', '\t', '\x2', 
		'\x39', '>', '\x5', '\b', '\x5', '\x2', ':', '>', '\x5', '\n', '\x6', 
		'\x2', ';', '>', '\x5', '\f', '\a', '\x2', '<', '>', '\x5', '\xE', '\b', 
		'\x2', '=', '\x36', '\x3', '\x2', '\x2', '\x2', '=', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '=', '\x38', '\x3', '\x2', '\x2', '\x2', '=', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '=', ':', '\x3', '\x2', '\x2', '\x2', '=', ';', '\x3', 
		'\x2', '\x2', '\x2', '=', '<', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x3', 
		'\x2', '\x2', '\x2', '?', '@', '\a', '\x3', '\x2', '\x2', '@', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '=', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x44', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x46', 
		'G', '\a', ')', '\x2', '\x2', 'G', 'H', '\x5', '\x30', '\x19', '\x2', 
		'H', 'I', '\x5', '\x32', '\x1A', '\x2', 'I', 'J', '\x5', '\x12', '\n', 
		'\x2', 'J', 'K', '\x5', '\x16', '\f', '\x2', 'K', '\x5', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'M', '\a', '$', '\x2', '\x2', 'M', 'N', '\x5', '\x30', 
		'\x19', '\x2', 'N', 'S', '\x5', '\x32', '\x1A', '\x2', 'O', 'P', '\a', 
		'\x4', '\x2', '\x2', 'P', 'Q', '\x5', '(', '\x15', '\x2', 'Q', 'R', '\a', 
		'\x5', '\x2', '\x2', 'R', 'T', '\x3', '\x2', '\x2', '\x2', 'S', 'O', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'V', '\x5', '\"', '\x12', '\x2', 'V', '\a', 
		'\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '+', '\x2', '\x2', 'X', 'Y', 
		'\x5', '\x32', '\x1A', '\x2', 'Y', '_', '\a', '\x6', '\x2', '\x2', 'Z', 
		'[', '\x5', '\x10', '\t', '\x2', '[', '\\', '\a', '\x3', '\x2', '\x2', 
		'\\', '^', '\x3', '\x2', '\x2', '\x2', ']', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '^', '\x61', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', 
		'\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\a', '\a', '\x2', '\x2', '\x63', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\a', '/', '\x2', '\x2', '\x65', '\x66', '\x5', '\x32', 
		'\x1A', '\x2', '\x66', 'g', '\a', '\b', '\x2', '\x2', 'g', 'h', '\x5', 
		'\x34', '\x1B', '\x2', 'h', 'i', '\a', '\t', '\x2', '\x2', 'i', 'r', '\a', 
		'\x6', '\x2', '\x2', 'j', 'm', '\x5', '\x1C', '\xF', '\x2', 'k', 'm', 
		'\x5', '\x1A', '\xE', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'l', 
		'k', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', '\x3', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 
		'p', 'l', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 
		's', 'u', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\a', '\a', '\x2', '\x2', 'v', '\v', '\x3', '\x2', '\x2', '\x2', 
		'w', 'x', '\a', '\x30', '\x2', '\x2', 'x', 'y', '\x5', '\x32', '\x1A', 
		'\x2', 'y', 'z', '\a', '\b', '\x2', '\x2', 'z', '{', '\x5', '\x34', '\x1B', 
		'\x2', '{', '|', '\a', '\t', '\x2', '\x2', '|', '\x85', '\a', '\x6', '\x2', 
		'\x2', '}', '\x80', '\x5', '\x1C', '\xF', '\x2', '~', '\x80', '\x5', '\x1A', 
		'\xE', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\a', '\x3', '\x2', '\x2', '\x82', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x84', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 
		'\a', '\x2', '\x2', '\x89', '\r', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', '\x30', '\x2', '\x2', '\x8B', '\x90', '\x5', '\x32', '\x1A', 
		'\x2', '\x8C', '\x8D', '\a', '\n', '\x2', '\x2', '\x8D', '\x8F', '\x5', 
		'\x34', '\x1B', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x94', '\a', '\b', '\x2', '\x2', '\x94', '\x95', '\x5', '\x32', '\x1A', 
		'\x2', '\x95', '\x96', '\a', '\t', '\x2', '\x2', '\x96', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\a', '%', '\x2', '\x2', '\x98', 
		'\x99', '\x5', '\x30', '\x19', '\x2', '\x99', '\xA5', '\x5', '\x32', '\x1A', 
		'\x2', '\x9A', '\x9B', '\a', '\x4', '\x2', '\x2', '\x9B', '\x9C', '\x5', 
		'(', '\x15', '\x2', '\x9C', '\x9D', '\a', '\x5', '\x2', '\x2', '\x9D', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '\n', '\x2', 
		'\x2', '\x9F', '\xA1', '\x5', '\x32', '\x1A', '\x2', '\xA0', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\x11', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xB0', '\a', 
		'\b', '\x2', '\x2', '\xA8', '\xAD', '\x5', '\x14', '\v', '\x2', '\xA9', 
		'\xAA', '\a', '\n', '\x2', '\x2', '\xAA', '\xAC', '\x5', '\x14', '\v', 
		'\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', '\t', '\x2', 
		'\x2', '\xB3', '\x13', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		'%', '\x2', '\x2', '\xB5', '\xB6', '\x5', '\x30', '\x19', '\x2', '\xB6', 
		'\xBB', '\x5', '\x32', '\x1A', '\x2', '\xB7', '\xB8', '\a', '\x4', '\x2', 
		'\x2', '\xB8', '\xB9', '\x5', '(', '\x15', '\x2', '\xB9', '\xBA', '\a', 
		'\x5', '\x2', '\x2', '\xBA', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\x15', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC9', '\a', 
		'\x6', '\x2', '\x2', '\xBE', '\xBF', '\x5', '\x18', '\r', '\x2', '\xBF', 
		'\xC0', '\a', '\x3', '\x2', '\x2', '\xC0', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC1', '\xC3', '\x5', '\x1E', '\x10', '\x2', '\xC2', '\xC4', '\a', 
		'\x3', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xCA', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xC9', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\a', '\a', '\x2', 
		'\x2', '\xCD', '\x17', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xD5', '\x5', 
		'\x1A', '\xE', '\x2', '\xCF', '\xD5', '\x5', '\x1C', '\xF', '\x2', '\xD0', 
		'\xD5', '\x5', ' ', '\x11', '\x2', '\xD1', '\xD5', '\x5', '\x6', '\x4', 
		'\x2', '\xD2', '\xD5', '\x5', '\x10', '\t', '\x2', '\xD3', '\xD5', '\x5', 
		'&', '\x14', '\x2', '\xD4', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD4', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD2', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x5', '\x32', '\x1A', 
		'\x2', '\xD7', '\xE0', '\a', '\b', '\x2', '\x2', '\xD8', '\xDD', '\x5', 
		'&', '\x14', '\x2', '\xD9', '\xDA', '\a', '\n', '\x2', '\x2', '\xDA', 
		'\xDC', '\x5', '&', '\x14', '\x2', '\xDB', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE2', 
		'\xE3', '\a', '\t', '\x2', '\x2', '\xE3', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\xE4', '\xE5', '\x5', ',', '\x17', '\x2', '\xE5', '\xE6', '\t', 
		'\x2', '\x2', '\x2', '\xE6', '\xE7', '\x5', '&', '\x14', '\x2', '\xE7', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', '&', '\x2', 
		'\x2', '\xE9', '\xEA', '\x5', '&', '\x14', '\x2', '\xEA', '\xF2', '\x5', 
		'\x16', '\f', '\x2', '\xEB', '\xEC', '\a', '(', '\x2', '\x2', '\xEC', 
		'\xED', '\a', '&', '\x2', '\x2', '\xED', '\xEE', '\x5', '&', '\x14', '\x2', 
		'\xEE', '\xEF', '\x5', '\x16', '\f', '\x2', '\xEF', '\xF1', '\x3', '\x2', 
		'\x2', '\x2', '\xF0', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF4', 
		'\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\x3', '\x2', '\x2', '\x2', 
		'\xF2', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF7', '\x3', '\x2', 
		'\x2', '\x2', '\xF4', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', 
		'\a', '(', '\x2', '\x2', '\xF6', '\xF8', '\x5', '\x16', '\f', '\x2', '\xF7', 
		'\xF5', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', '\x3', '\x2', '\x2', 
		'\x2', '\xF8', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFB', '\a', 
		'-', '\x2', '\x2', '\xFA', '\xFC', '\x5', '&', '\x14', '\x2', '\xFB', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', '\xFC', '!', '\x3', '\x2', '\x2', '\x2', '\xFD', '\x100', '\a', 
		'\v', '\x2', '\x2', '\xFE', '\x101', '\x5', '&', '\x14', '\x2', '\xFF', 
		'\x101', '\x5', '$', '\x13', '\x2', '\x100', '\xFE', '\x3', '\x2', '\x2', 
		'\x2', '\x100', '\xFF', '\x3', '\x2', '\x2', '\x2', '\x101', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x102', '\x103', '\a', '\x6', '\x2', '\x2', '\x103', 
		'\x108', '\x5', '&', '\x14', '\x2', '\x104', '\x105', '\a', '\n', '\x2', 
		'\x2', '\x105', '\x107', '\x5', '&', '\x14', '\x2', '\x106', '\x104', 
		'\x3', '\x2', '\x2', '\x2', '\x107', '\x10A', '\x3', '\x2', '\x2', '\x2', 
		'\x108', '\x109', '\x3', '\x2', '\x2', '\x2', '\x108', '\x106', '\x3', 
		'\x2', '\x2', '\x2', '\x109', '\x10B', '\x3', '\x2', '\x2', '\x2', '\x10A', 
		'\x108', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x10C', '\a', '\a', '\x2', 
		'\x2', '\x10C', '%', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x10E', '\b', 
		'\x14', '\x1', '\x2', '\x10E', '\x10F', '\a', '\b', '\x2', '\x2', '\x10F', 
		'\x110', '\x5', '&', '\x14', '\x2', '\x110', '\x111', '\a', '\t', '\x2', 
		'\x2', '\x111', '\x117', '\x3', '\x2', '\x2', '\x2', '\x112', '\x113', 
		'\t', '\x3', '\x2', '\x2', '\x113', '\x117', '\x5', '&', '\x14', '\v', 
		'\x114', '\x117', '\x5', '*', '\x16', '\x2', '\x115', '\x117', '\x5', 
		'\x32', '\x1A', '\x2', '\x116', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x116', 
		'\x112', '\x3', '\x2', '\x2', '\x2', '\x116', '\x114', '\x3', '\x2', '\x2', 
		'\x2', '\x116', '\x115', '\x3', '\x2', '\x2', '\x2', '\x117', '\x12C', 
		'\x3', '\x2', '\x2', '\x2', '\x118', '\x119', '\f', '\n', '\x2', '\x2', 
		'\x119', '\x11A', '\t', '\x4', '\x2', '\x2', '\x11A', '\x12B', '\x5', 
		'&', '\x14', '\v', '\x11B', '\x11C', '\f', '\t', '\x2', '\x2', '\x11C', 
		'\x11D', '\t', '\x5', '\x2', '\x2', '\x11D', '\x12B', '\x5', '&', '\x14', 
		'\n', '\x11E', '\x11F', '\f', '\b', '\x2', '\x2', '\x11F', '\x120', '\t', 
		'\x6', '\x2', '\x2', '\x120', '\x12B', '\x5', '&', '\x14', '\t', '\x121', 
		'\x122', '\f', '\a', '\x2', '\x2', '\x122', '\x123', '\t', '\a', '\x2', 
		'\x2', '\x123', '\x12B', '\x5', '&', '\x14', '\b', '\x124', '\x125', '\f', 
		'\x6', '\x2', '\x2', '\x125', '\x126', '\t', '\b', '\x2', '\x2', '\x126', 
		'\x12B', '\x5', '&', '\x14', '\a', '\x127', '\x128', '\f', '\x5', '\x2', 
		'\x2', '\x128', '\x129', '\t', '\t', '\x2', '\x2', '\x129', '\x12B', '\x5', 
		'&', '\x14', '\x6', '\x12A', '\x118', '\x3', '\x2', '\x2', '\x2', '\x12A', 
		'\x11B', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x11E', '\x3', '\x2', '\x2', 
		'\x2', '\x12A', '\x121', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x124', 
		'\x3', '\x2', '\x2', '\x2', '\x12A', '\x127', '\x3', '\x2', '\x2', '\x2', 
		'\x12B', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12A', '\x3', 
		'\x2', '\x2', '\x2', '\x12C', '\x12D', '\x3', '\x2', '\x2', '\x2', '\x12D', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x12E', '\x12C', '\x3', '\x2', '\x2', 
		'\x2', '\x12F', '\x132', '\a', '\x33', '\x2', '\x2', '\x130', '\x132', 
		'\x5', '\x34', '\x1B', '\x2', '\x131', '\x12F', '\x3', '\x2', '\x2', '\x2', 
		'\x131', '\x130', '\x3', '\x2', '\x2', '\x2', '\x132', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x133', '\x13A', '\a', '\x33', '\x2', '\x2', '\x134', '\x13A', 
		'\a', '\x34', '\x2', '\x2', '\x135', '\x13A', '\a', '\x35', '\x2', '\x2', 
		'\x136', '\x13A', '\a', '\x31', '\x2', '\x2', '\x137', '\x13A', '\x5', 
		'\x1A', '\xE', '\x2', '\x138', '\x13A', '\x5', ',', '\x17', '\x2', '\x139', 
		'\x133', '\x3', '\x2', '\x2', '\x2', '\x139', '\x134', '\x3', '\x2', '\x2', 
		'\x2', '\x139', '\x135', '\x3', '\x2', '\x2', '\x2', '\x139', '\x136', 
		'\x3', '\x2', '\x2', '\x2', '\x139', '\x137', '\x3', '\x2', '\x2', '\x2', 
		'\x139', '\x138', '\x3', '\x2', '\x2', '\x2', '\x13A', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x13B', '\x13E', '\x5', '.', '\x18', '\x2', '\x13C', '\x13D', 
		'\a', '#', '\x2', '\x2', '\x13D', '\x13F', '\x5', '.', '\x18', '\x2', 
		'\x13E', '\x13C', '\x3', '\x2', '\x2', '\x2', '\x13E', '\x13F', '\x3', 
		'\x2', '\x2', '\x2', '\x13F', '-', '\x3', '\x2', '\x2', '\x2', '\x140', 
		'\x145', '\x5', '\x34', '\x1B', '\x2', '\x141', '\x142', '\a', '\x4', 
		'\x2', '\x2', '\x142', '\x143', '\x5', '(', '\x15', '\x2', '\x143', '\x144', 
		'\a', '\x5', '\x2', '\x2', '\x144', '\x146', '\x3', '\x2', '\x2', '\x2', 
		'\x145', '\x141', '\x3', '\x2', '\x2', '\x2', '\x145', '\x146', '\x3', 
		'\x2', '\x2', '\x2', '\x146', '/', '\x3', '\x2', '\x2', '\x2', '\x147', 
		'\x14F', '\x5', '\x34', '\x1B', '\x2', '\x148', '\x14F', '\a', ',', '\x2', 
		'\x2', '\x149', '\x14F', '\a', '\'', '\x2', '\x2', '\x14A', '\x14F', '\a', 
		'.', '\x2', '\x2', '\x14B', '\x14F', '\a', '*', '\x2', '\x2', '\x14C', 
		'\x14F', '\a', ')', '\x2', '\x2', '\x14D', '\x14F', '\a', '\x30', '\x2', 
		'\x2', '\x14E', '\x147', '\x3', '\x2', '\x2', '\x2', '\x14E', '\x148', 
		'\x3', '\x2', '\x2', '\x2', '\x14E', '\x149', '\x3', '\x2', '\x2', '\x2', 
		'\x14E', '\x14A', '\x3', '\x2', '\x2', '\x2', '\x14E', '\x14B', '\x3', 
		'\x2', '\x2', '\x2', '\x14E', '\x14C', '\x3', '\x2', '\x2', '\x2', '\x14E', 
		'\x14D', '\x3', '\x2', '\x2', '\x2', '\x14F', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x150', '\x151', '\a', '\x32', '\x2', '\x2', '\x151', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\x152', '\x153', '\a', '\x32', '\x2', '\x2', 
		'\x153', '\x35', '\x3', '\x2', '\x2', '\x2', '#', '=', '\x43', 'S', '_', 
		'l', 'r', '\x7F', '\x85', '\x90', '\xA2', '\xA5', '\xAD', '\xB0', '\xBB', 
		'\xC3', '\xC5', '\xC9', '\xD4', '\xDD', '\xE0', '\xF2', '\xF7', '\xFB', 
		'\x100', '\x108', '\x116', '\x12A', '\x12C', '\x131', '\x139', '\x13E', 
		'\x145', '\x14E',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
