//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DaedalusParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DaedalusParser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DaedalusParserParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IDaedalusParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] DaedalusParserParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] DaedalusParserParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDef([NotNull] DaedalusParserParser.FunctionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDef([NotNull] DaedalusParserParser.FunctionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] DaedalusParserParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] DaedalusParserParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementBlock([NotNull] DaedalusParserParser.StatementBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementBlock([NotNull] DaedalusParserParser.StatementBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] DaedalusParserParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] DaedalusParserParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] DaedalusParserParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] DaedalusParserParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] DaedalusParserParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] DaedalusParserParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] DaedalusParserParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] DaedalusParserParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] DaedalusParserParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] DaedalusParserParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] DaedalusParserParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] DaedalusParserParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.constDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDef([NotNull] DaedalusParserParser.ConstDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.constDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDef([NotNull] DaedalusParserParser.ConstDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDef([NotNull] DaedalusParserParser.ClassDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDef([NotNull] DaedalusParserParser.ClassDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.prototypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrototypeDef([NotNull] DaedalusParserParser.PrototypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.prototypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrototypeDef([NotNull] DaedalusParserParser.PrototypeDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.instanceDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceDef([NotNull] DaedalusParserParser.InstanceDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.instanceDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceDef([NotNull] DaedalusParserParser.InstanceDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.instanceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceDecl([NotNull] DaedalusParserParser.InstanceDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.instanceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceDecl([NotNull] DaedalusParserParser.InstanceDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.constAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstAssignment([NotNull] DaedalusParserParser.ConstAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.constAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstAssignment([NotNull] DaedalusParserParser.ConstAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayLiteral([NotNull] DaedalusParserParser.ArrayLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayLiteral([NotNull] DaedalusParserParser.ArrayLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] DaedalusParserParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] DaedalusParserParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.logicAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicAnd([NotNull] DaedalusParserParser.LogicAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.logicAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicAnd([NotNull] DaedalusParserParser.LogicAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitOr([NotNull] DaedalusParserParser.BitOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitOr([NotNull] DaedalusParserParser.BitOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitAnd([NotNull] DaedalusParserParser.BitAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitAnd([NotNull] DaedalusParserParser.BitAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqual([NotNull] DaedalusParserParser.EqualContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqual([NotNull] DaedalusParserParser.EqualContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] DaedalusParserParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] DaedalusParserParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitShift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitShift([NotNull] DaedalusParserParser.BitShiftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitShift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitShift([NotNull] DaedalusParserParser.BitShiftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] DaedalusParserParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] DaedalusParserParser.AddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult([NotNull] DaedalusParserParser.MultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult([NotNull] DaedalusParserParser.MultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary([NotNull] DaedalusParserParser.UnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary([NotNull] DaedalusParserParser.UnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.simpleValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleValue([NotNull] DaedalusParserParser.SimpleValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.simpleValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleValue([NotNull] DaedalusParserParser.SimpleValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] DaedalusParserParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] DaedalusParserParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.complexReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexReference([NotNull] DaedalusParserParser.ComplexReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.complexReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexReference([NotNull] DaedalusParserParser.ComplexReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.complexReferenceNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexReferenceNode([NotNull] DaedalusParserParser.ComplexReferenceNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.complexReferenceNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexReferenceNode([NotNull] DaedalusParserParser.ComplexReferenceNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeReference([NotNull] DaedalusParserParser.TypeReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeReference([NotNull] DaedalusParserParser.TypeReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.referenceNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceNode([NotNull] DaedalusParserParser.ReferenceNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.referenceNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceNode([NotNull] DaedalusParserParser.ReferenceNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.nameNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameNode([NotNull] DaedalusParserParser.NameNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.nameNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameNode([NotNull] DaedalusParserParser.NameNodeContext context);
}
} // namespace DaedalusParser
