//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DaedalusParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DaedalusParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDaedalusParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class DaedalusParserBaseListener : IDaedalusParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] DaedalusParserParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] DaedalusParserParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDef([NotNull] DaedalusParserParser.FunctionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.functionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDef([NotNull] DaedalusParserParser.FunctionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] DaedalusParserParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] DaedalusParserParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementBlock([NotNull] DaedalusParserParser.StatementBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementBlock([NotNull] DaedalusParserParser.StatementBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] DaedalusParserParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] DaedalusParserParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] DaedalusParserParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] DaedalusParserParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] DaedalusParserParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] DaedalusParserParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] DaedalusParserParser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.ifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] DaedalusParserParser.IfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] DaedalusParserParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] DaedalusParserParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] DaedalusParserParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] DaedalusParserParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.constDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDef([NotNull] DaedalusParserParser.ConstDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.constDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDef([NotNull] DaedalusParserParser.ConstDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] DaedalusParserParser.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] DaedalusParserParser.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.prototypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrototypeDef([NotNull] DaedalusParserParser.PrototypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.prototypeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrototypeDef([NotNull] DaedalusParserParser.PrototypeDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.instanceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceDef([NotNull] DaedalusParserParser.InstanceDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.instanceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceDef([NotNull] DaedalusParserParser.InstanceDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.instanceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstanceDecl([NotNull] DaedalusParserParser.InstanceDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.instanceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstanceDecl([NotNull] DaedalusParserParser.InstanceDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.constAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstAssignment([NotNull] DaedalusParserParser.ConstAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.constAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstAssignment([NotNull] DaedalusParserParser.ConstAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] DaedalusParserParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] DaedalusParserParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] DaedalusParserParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] DaedalusParserParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.logicAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicAnd([NotNull] DaedalusParserParser.LogicAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.logicAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicAnd([NotNull] DaedalusParserParser.LogicAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitOr([NotNull] DaedalusParserParser.BitOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitOr([NotNull] DaedalusParserParser.BitOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitAnd([NotNull] DaedalusParserParser.BitAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitAnd([NotNull] DaedalusParserParser.BitAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.equal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqual([NotNull] DaedalusParserParser.EqualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.equal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqual([NotNull] DaedalusParserParser.EqualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] DaedalusParserParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] DaedalusParserParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.bitShift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitShift([NotNull] DaedalusParserParser.BitShiftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.bitShift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitShift([NotNull] DaedalusParserParser.BitShiftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] DaedalusParserParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] DaedalusParserParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult([NotNull] DaedalusParserParser.MultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult([NotNull] DaedalusParserParser.MultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary([NotNull] DaedalusParserParser.UnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary([NotNull] DaedalusParserParser.UnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.simpleValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleValue([NotNull] DaedalusParserParser.SimpleValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.simpleValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleValue([NotNull] DaedalusParserParser.SimpleValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] DaedalusParserParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] DaedalusParserParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.complexReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReference([NotNull] DaedalusParserParser.ComplexReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.complexReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReference([NotNull] DaedalusParserParser.ComplexReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.complexReferenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexReferenceNode([NotNull] DaedalusParserParser.ComplexReferenceNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.complexReferenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexReferenceNode([NotNull] DaedalusParserParser.ComplexReferenceNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReference([NotNull] DaedalusParserParser.TypeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReference([NotNull] DaedalusParserParser.TypeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.referenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceNode([NotNull] DaedalusParserParser.ReferenceNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.referenceNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceNode([NotNull] DaedalusParserParser.ReferenceNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DaedalusParserParser.nameNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameNode([NotNull] DaedalusParserParser.NameNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DaedalusParserParser.nameNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameNode([NotNull] DaedalusParserParser.NameNodeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace DaedalusParser
